name: Generate and Serve Exam Papers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Exam Papers
        run: python script.py

      - name: Serve Exam Papers
        run: |
          echo "Starting live server..."
          docker run -d --rm --name exam-papers -v $GITHUB_WORKSPACE:/var/www/html -p 8080:80 webdevops/php-apache:8.0
          echo "Live server started on port 8080."

      - name: Print URL
        run: echo "View the exam paper at http://localhost:8080/exam_paper.html"
