name: Generate Exam Papers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Exam Papers
        run: python script.py

      - name: Move HTML Exam Papers to Root
        run: |
          for file in $GITHUB_WORKSPACE/*.html; do
            mv "$file" "$GITHUB_WORKSPACE/$(basename $file)"
          done

      - name: Upload Exam Paper Artifact
        uses: actions/upload-artifact@v2
        with:
          name: exam-papers
          path: $GITHUB_WORKSPACE
